<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /home/jezm/sandbox/peer1/clippy/app/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'clippy' => 
    array (
      'adapter' => 'sqlite',
      'connection' => 
      array (
        'dsn' => 'sqlite:data/clippy.sq3',
      ),
    ),
    'default' => 'clippy',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap--conf.php');
return $conf;