<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'BaseClipping' => 'clippy/om/BaseClipping.php',
  'BaseClippingPeer' => 'clippy/om/BaseClippingPeer.php',
  'BaseClippingQuery' => 'clippy/om/BaseClippingQuery.php',
  'Clipping' => 'clippy/Clipping.php',
  'ClippingPeer' => 'clippy/ClippingPeer.php',
  'ClippingQuery' => 'clippy/ClippingQuery.php',
  'ClippingTableMap' => 'clippy/map/ClippingTableMap.php',
);