<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'BaseClipping' => 'om/BaseClipping.php',
  'BaseClippingPeer' => 'om/BaseClippingPeer.php',
  'BaseClippingQuery' => 'om/BaseClippingQuery.php',
  'Clipping' => 'Clipping.php',
  'ClippingPeer' => 'ClippingPeer.php',
  'ClippingQuery' => 'ClippingQuery.php',
  'ClippingTableMap' => 'map/ClippingTableMap.php',
);